

all:

clean:
	cd abramowitz; make clean
	cd billiards; make clean
	cd chiral-bag; make clean
	cd continued-frobenius; make clean
	cd de-rham; make clean
	cd farey; make clean
	cd free-group; make clean
	cd gap; make clean
	cd hurwitz; make clean
	cd ising; make clean
	cd modular; make clean
	cd num-theory; make clean
	cd plouffe; make clean
	cd schroedinger; make clean
	cd wavelet; make clean
	cd weyl; make clean
	cd zeta-hamiltonian; make clean

realclean: clean
	cd abramowitz; make realclean
	cd billiards; make realclean
	cd chiral-bag; make realclean
	cd continued-frobenius; make realclean
	cd de-rham; make realclean
	cd farey; make realclean
	cd free-group; make realclean
	cd gap; make realclean
	cd hurwitz; make realclean
	cd ising; make realclean
	cd modular; make realclean
	cd num-theory; make realclean
	cd plouffe; make realclean
	cd schroedinger; make realclean
	cd wavelet; make realclean
	cd weyl; make realclean
	cd zeta-hamiltonian; make realclean
