

clean:
	cd farey; make clean
	cd file; make clean
	cd speectra; make clean
	cd stoch; make clean

realclean: clean
	cd farey; make realclean
	cd file; make realclean
	cd speectra; make realclean
	cd stoch; make realclean

