#! /bin/sh

# takelog junk junkl
renorm junk j 1
cat j.flo | ../../../../bin/flo2mtv |mtvtoppm | ppmtogif > junk.gif


# cat junkr.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > junk.gif
# cat sym.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > sym.gif
# reclamp sum sumc 1
# cat sumc.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > sum.gif
# reclamp mult multc 1
# cat multc.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > mult.gif
# reclamp double doublec 1
# cat doublec.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > double.gif
# renorm fnu junkr 0.2
# cat junkr.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > fnu.gif



