#! /bin/sh

# cat ereal.flo | /home/linas/linas/fractal-tools/bin/flo2mtv |mtvtoppm | ppmtogif > ereal.gif
# cat efrac.flo | /home/linas/linas/fractal-tools/bin/flo2mtv |mtvtoppm | ppmtogif > efrac.gif
cat blob.flo | /home/linas/linas/fractal-tools/bin/flo2mtv |mtvtoppm | ppmtogif > blob.gif

# cat junk.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > junk.gif
# cat sym.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > sym.gif
# reclamp sum sumc 1
# cat sumc.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > sum.gif
# reclamp mult multc 1
# cat multc.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > mult.gif
# reclamp double doublec 1
# cat doublec.flo | /usr/home/src/tools/bin/flo2mtv |mtvtoppm | ppmtogif > double.gif
