#! /bin/sh

# cat junk.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > j.png
# cat mult.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > m.png

# ../../generate/renorm bern j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > bern.png

# ../../generate/renorm bern-sq j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > bern-sq.png

# ../../generate/takelog bern lo 
# ../../generate/renorm lo j 1.0 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > bernlo.png

# ../../generate/renorm nocarry j 1.0 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > nocarry.png

# ../../generate/renorm notent j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > notent.png

# ../../generate/renorm nofeig j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > nofeig.png

../../generate/renorm island j 0.5 0
cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > island.png

# ../../generate/renorm mang-carry-1 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-1.png

# ../../generate/renorm mang-carry-2 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-2.png

# ../../generate/renorm mang-carry-3 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-3.png

# ../../generate/renorm mang-carry-4 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-4.png

# ../../generate/renorm mang-carry-5 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-5.png

# ../../generate/renorm mang-carry-6 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-6.png

# ../../generate/renorm mang-carry-1-less j 3 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-1-less.png

# ../../generate/renorm mang-carry-1-more j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-1-more.png

# ../../generate/renorm mang-carry-mod-2 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-mod-2.png

# ../../generate/renorm mang-carry-mod-3 j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-carry-mod-3.png

# ../../generate/renorm mang-flip-mod j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > mang-flip-mod.png

# ../../generate/renorm tent j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > tent.png

# ../../generate/renorm tenty j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > tenty.png

# ../../generate/renorm tent-4K j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > tent-4K.png

# ../../generate/renorm berny j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > berny.png

# ../../generate/renorm feigy j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > feigy.png

# ../../generate/renorm feig-4K j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > feig-4K.png

# ../../generate/renorm feig-4K-fat j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > feig-4K-fat.png

# ../../generate/renorm feig j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > feig.png

# ../../generate/renorm bigly j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > bern-4K.png

# ../../generate/renorm bern-1360 j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > bern-1360.png

# ../../generate/renorm tent-big j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > tent-4K.png

# ../../generate/renorm sidebern j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sidebern.png

# ../../generate/renorm sidetarp j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sidetarp.png

# ../../generate/renorm sidetent j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sidetent.png

# ../../generate/renorm sideflip j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sideflip.png

# ../../generate/renorm unmap j 0.2 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > unmap.png

# ../../generate/renorm fp-eig j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > fp-eig.png

# ../../generate/takelog fp-eig-12 lo
# ../../generate/renorm lo j 1.5 0
# ../../generate/renorm fp-eig-12 j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > fp-eig-12.png

# ../../generate/renorm fp-eig-60 j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > fp-eig-60.png

# ../../generate/renorm carry-add j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > carry-add.png

# ../../generate/renorm carry-prod j 2 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > carry-prod.png

# ../../generate/renorm carry-prod-size j 2 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > carry-prod-size.png

# ../../generate/renorm step-08 j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > step-0.8.png

# ../../generate/renorm step-07 j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > step-0.7.png

# ../../generate/renorm treek j 1500 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > treek.png

# ../../generate/renorm julie j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > julie.png

# ../../generate/renorm matrix-6 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.6.png

# ../../generate/renorm matrix-7 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.7.png

# ../../generate/renorm matrix-8 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.8.png

# ../../generate/renorm matrix-9 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.9.png

# ../../generate/renorm matrix-55 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.55.png

# ../../generate/renorm matrix-65 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.65.png

# ../../generate/renorm matrix-75 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.75.png

# ../../generate/renorm matrix-85 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.85.png

# ../../generate/renorm matrix-95 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.95.png

# ../../generate/renorm matrix-99 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.99.png

# ../../generate/renorm matrix-999 j 1.5 0
# ../../generate/abs j j
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > matrix-0.999.png

# ../../generate/renorm berg j 1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > berg.png

# ../../generate/renorm psidelt j 0.7 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > psidelt.png

# ffmpeg -framerate 25 -i matrix-0.%05d.png -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p output.mp4
