#! /bin/sh

# cat wind-circ.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > wind-circ.png
cat wind-tri.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > wind-tri.png

# ../../generate/renorm recur-circ j 0.01 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-circ.png

# ../../generate/takelog recur-circ jlog
# ../../generate/renorm jlog j 0.1 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > j.png

# ../../generate/renorm recur-saw j 0.005 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-saw.png

# ../../generate/renorm recur-tri j 0.0032 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-tri.png

# ../../generate/renorm recur-saw-q j 0.005 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-saw-q.png

# ../../generate/renorm recur-saw-3e j 0.005 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-saw-3e.png
