#! /bin/sh

# cat wind-circ.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > wind-circ.png
# cat wind-saw.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > wind-saw.png

# ../../generate/renorm recur-circ j 0.01 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-circ.png

# ../../generate/renorm recur-saw j 0.005 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-saw.png

../../generate/renorm recur-saw-q j 0.005 0
cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > recur-saw-q.png
