#! /bin/sh


# This used for the sidorov toungues picture
# ../../generate/renorm sid j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sido.png

# 0.375 = 0.5 * 3/4 because the x=1 line was incorrectly normalized.
# and the factor of 0.5 to make it green
# ../../generate/renorm sido-dense-800x400-60 j 0.375 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sido-den.png

../../generate/renorm sido-dense-400x200-60 j 0.375 0
cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sido-den.png

# ../../generate/renorm sido-fur j 0.5 0
# cat j.flo | ../../image/flo2mtv |mtvtoppm | pnmtopng > sido-fur.png
