
/* sym-fun.C
 *
 * Symmetry functions generated by the Minkowski symmetery group.
 *
 * Linas Vepstas October 2004
 */

#include <math.h>
#include <stdio.h>

#include "Farey.h"

main (int argc, char *argv[])
{
	int i;
	ContinuedFraction f;
	f.SetEvenize();


	int nmax = 431;
	for (i=0; i<nmax; i++)
	{
		double x = ((double) 2*i+1)/ ((double) (2*nmax));

#define SAWTOOTH
#ifdef SAWTOOTH
		// this is what continued-fraction truncation looks like 
		// in binary-digit space
		double z = InvFarey(x);
		double y = 1.0/z;
		y -= floor (y);
		f.SetReal (y);
		double qy = f.ToFarey();
#endif

#ifdef BERNOULLI
		// this is what binary-digit truncation looks like in
		// in continued fraction space.
		f.SetReal (x);
		double yb = f.ToFarey();
		yb *= 2.0;
		yb -= floor (yb);
		double y = InvFarey (yb);
#endif

		printf ("%5d	%8.6g	%8.6g\n", i, x, y);

	}
}

