
/* sym-fun.C
 *
 * Symmetry functions generated by the Minkowski symmetery group.
 *
 * Linas Vepstas October 2004
 */

#include <math.h>
#include <stdio.h>

#include "Farey.h"

main (int argc, char *argv[])
{
	int i;
	ContinuedFraction f;
	f.SetEvenize();


	int nmax = 431;
	for (i=0; i<nmax; i++)
	{
		double x = ((double) 2*i+1)/ ((double) (2*nmax));

		double z = InvFarey(x);

		double y = 1.0/z;
		y -= floor (y);
		
		f.SetReal (y);
		double qy = f.ToFarey();

		double yy = (1.0+x)/x;
		yy -= floor (yy);

		double xx = 1.0/x;
		xx -= floor (xx);

		printf ("%5d	%8.6g	%8.6g	%8.6g	%8.6g	%8.6g\n", i, x, xx, yy, xx-yy, qy);

	}
}

